huaweicloud/huaweicloud-csi-driver

pkg/sfs/controllerserver.go, pkg/sfs/share.go
has been checked in k8s cluster
=> fix: sfs createVolume func add idempotency check

README.md, README_CN.md, deploy/sfs-csi-plugin/kubernetes/csi-sfs-controller.yaml, deploy/sfs-csi-plugin/kubernetes/csi-sfs-node.yaml, docs/sfs/sfs-share.md, docs/sfs/sfs.md, examples/sfs-csi-plugin/kubernetes/share/pod.yaml, examples/sfs-csi-plugin/kubernetes/share/pvc.yaml, examples/sfs-csi-plugin/kubernetes/share/sc.yaml
add sfsplugin documents.
modify sfs external-plugin version
=> feat: sfs add documents

README.md, README_CN.md
Revert this when we published the SFS image
=> Remove SFS support from README

README.md, README_CN.md, deploy/sfsturbo-csi-plugin/cloud-config, docs/cloud-config.md, docs/sfsturbo/sfsturbo-dynamic.md, docs/sfsturbo/sfsturbo-resize.md, docs/sfsturbo/sfsturbo.md, examples/sfsturbo-csi-plugin/kubernetes/dynamic/pod.yaml, examples/sfsturbo-csi-plugin/kubernetes/dynamic/pvc.yaml, examples/sfsturbo-csi-plugin/kubernetes/dynamic/sc.yaml, examples/sfsturbo-csi-plugin/kubernetes/resize/pod.yaml, examples/sfsturbo-csi-plugin/kubernetes/resize/pvc.yaml, examples/sfsturbo-csi-plugin/kubernetes/resize/pvc2.yaml, examples/sfsturbo-csi-plugin/kubernetes/resize/sc.yaml, test/sfsturbo/dynamic.sh, test/sfsturbo/resize.sh
docker version 20.10.2 
kubernetes version 1.22.0
====== Start Test SFS Turbo(dynamic)
[storageclass.storage.k8s.io/sfsturbo-sc](http://storageclass.storage.k8s.io/sfsturbo-sc) created
persistentvolumeclaim/sfsturbo-pvc-dynamic created
pod/sfsturbo-nginx-dynamic created
pod "sfsturbo-nginx-dynamic" deleted
persistentvolumeclaim "sfsturbo-pvc-dynamic" deleted
[storageclass.storage.k8s.io](http://storageclass.storage.k8s.io/) "sfsturbo-sc" deleted
------ PASS: SFS Turbo(dynamic) Test
====== Start Test SFS Turbo(resize)
[storageclass.storage.k8s.io/sfsturbo-sc](http://storageclass.storage.k8s.io/sfsturbo-sc) created
persistentvolumeclaim/sfsturbo-pvc-resize created
pod/sfsturbo-nginx-resize created
persistentvolumeclaim/sfsturbo-pvc-resize configured
pod "sfsturbo-nginx-resize" deleted …
=> Feat sfsturbo document

README.md, README_CN.md
>
> /kind bug
> /kind design
> /kind flake
add sfs MD information
Fixes #
```release-note
```
```docs
```
=> feat: add sfs MD

cmd/sfs-csi-plugin/main.go, pkg/sfs/driver.go, pkg/sfs/nodeserver.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```
=> fix: sfs support get volume stats

Makefile, cmd/sfs-csi-plugin/main.go, hack/build-deploy-sfs.sh, hack/post-run-e2e.sh, hack/pre-run-e2e.sh, pkg/sfs/config/cloud.go, pkg/sfs/config/config.go, pkg/sfs/driver.go, pkg/sfs/nodeserver.go, test/sfs/sfs-test.sh
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> add support for IAM account authentication for SFS

test/config/cloud_test.go
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> fix test error issues caused by missing Env

deploy/sfs-csi-plugin/kubernetes/csi-sfs-controller.yaml, deploy/sfs-csi-plugin/kubernetes/csi-sfs-node.yaml
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> fix the image path

pkg/obs/controllerserver.go, pkg/obs/services/objects.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: implement the delete volume interface. 

pkg/obs/controllerserver.go, pkg/obs/services/buckets.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: add obs csi controller api

cmd/obs-csi-plugin/main.go, pkg/obs/driver.go, pkg/obs/mount.go, pkg/obs/nodeserver.go
>
> /kind bug
> /kind design
> /kind flake
add obs nodeserver code to master
Fixes #
```release-note
```
```docs
```
=> feat: add obs node server code

pkg/obs/nodeserver.go, pkg/obs/services/buckets.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: add obs csi nodeserver api

pkg/obs/controllerserver.go, pkg/obs/services/buckets.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: add obs csi controllerserver api 

.github/workflows/prow.yml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add prow github action

.github/workflows/prow.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```
=> Update prow github action version

pkg/obs/driver.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```
=> fix: obs support resizer

Makefile, cluster/images/obs-csi-plugin/Dockerfile, cluster/images/obs-csi-plugin/entrypoint.sh, cluster/images/obs-csi-plugin/socket-server.service
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```
=> fix: make the shell fit ubuntu and add systemd service

pkg/obs/controllerserver.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```
=> fix: obs csi controller expand return false

hack/deploy/obs/cloud-config, hack/deploy/obs/csi-obs-controller.yaml, hack/deploy/obs/csi-obs-driver.yaml, hack/deploy/obs/csi-obs-node.yaml, hack/deploy/obs/rbac-csi-obs-controller.yaml, hack/deploy/obs/rbac-csi-obs-node.yaml, hack/deploy/obs/rbac-csi-obs-secret.yaml, hack/post-run-obs-e2e.sh, hack/pre-run-obs-e2e.sh, hack/run-obs-e2e-test.sh, test/e2e/obs_csi_test.go
/kind feature
Fixes #
```
Ran 2 of 2 Specs in 40.240 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
```
```release-note
```
```docs
```
=> feat: add obs e2e test

deploy/obs-csi-plugin/cloud-config, deploy/obs-csi-plugin/kubernetes/csi-obs-controller.yaml, deploy/obs-csi-plugin/kubernetes/csi-obs-driver.yaml, deploy/obs-csi-plugin/kubernetes/csi-obs-node.yaml, deploy/obs-csi-plugin/kubernetes/rbac-csi-obs-controller.yaml, deploy/obs-csi-plugin/kubernetes/rbac-csi-obs-node.yaml, deploy/obs-csi-plugin/kubernetes/rbac-csi-obs-secret.yaml, examples/obs-csi-plugin/kubernetes/dynamic/pod.yaml, examples/obs-csi-plugin/kubernetes/dynamic/pvc.yaml, examples/obs-csi-plugin/kubernetes/dynamic/sc.yaml, examples/obs-csi-plugin/kubernetes/resize/pod.yaml, examples/obs-csi-plugin/kubernetes/resize/pvc.yaml, examples/obs-csi-plugin/kubernetes/resize/pvc2.yaml, examples/obs-csi-plugin/kubernetes/resize/sc.yaml
Fixes #
```release-note
```
```docs
```
=> feat: add obs csi yaml

go.mod, go.sum, pkg/obs/services/buckets.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/client_base.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/client_bucket.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/client_object.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/client_other.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/client_part.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/conf.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/const.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/convert.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/http.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/log.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/model_bucket.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/model_object.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/temporary_createSignedUrl.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/trait.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-obs/obs/transfer.go, vendor/modules.txt
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> fix: obsClient change RoundTripper

pkg/obs/services/buckets.go
>
> /kind bug
> /kind design
> /kind flake
remove obs csi bucket epid
Fixes #
```release-note
```
```docs
```
=> fix: remove obs Epid config

pkg/obs/nodeserver.go, pkg/obs/services/buckets.go
>
> /kind bug
> /kind design
> /kind flake
obs idempotent
Fixes #
```release-note
```
```docs
```
=> fix：obs idempotent

docs/sfsturbo/sfsturbo.md, docs/sfsturbo/use-existing-sfsturbo.md
Fixes #
```release-note
NONE
```
```docs
```
=> add a new example for SFS Turbo

cluster/images/obs-csi-plugin/socket-server.go, pkg/obs/controllerserver.go, pkg/obs/services/buckets.go
>
> /kind bug
> /kind design
> /kind flake
remove obs tag and support orange business services
Fixes #
```release-note
```
```docs
```
=> Obs remove tag

.github/workflows/ci.yml, .github/workflows/e2e-test.yml, hack/check-module.sh
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> run E2E tests based on labels

docs/evs/evs.md, docs/iam-policies.md, docs/obs/obs.md, docs/sfsturbo/sfsturbo.md, docs/user-policy.md
/kind cleanup
add csi minimum permission config document
Fixes #
```release-note
```
```docs
```
=> feat: add CSI IAM policies docs

pkg/evs/services/snapshots.go
>
> /kind bug
- fix: evs csi snapshot add Force parameter
Fixes #
```release-note
```
```docs
```
=> fix: evs csi snapshot add Force parameter

deploy/evs-csi-plugin/kubernetes/csi-evs-controller.yaml, deploy/evs-csi-plugin/kubernetes/csi-evs-node.yaml, docs/evs/evs.md, pkg/evs/controllerserver.go, pkg/evs/services/volumes.go, test/evs/snapshot.sh, vendor/github.com/chnsz/golangsdk/openstack/blockstorage/v2/volumes/doc.go, vendor/github.com/chnsz/golangsdk/openstack/blockstorage/v2/volumes/requests.go, vendor/github.com/chnsz/golangsdk/openstack/blockstorage/v2/volumes/results.go, vendor/github.com/chnsz/golangsdk/openstack/blockstorage/v2/volumes/urls.go, vendor/github.com/chnsz/golangsdk/openstack/blockstorage/v2/volumes/util.go, vendor/modules.txt
/kind feature
Fixes #
```release-note
Support for creating disks with the capacity less than 10G
```
```docs
```
=> feat: Support for creating disks with the capacity less than 10G

pkg/evs/controllerserver.go, pkg/evs/nodeserver.go, pkg/evs/services/volumes.go
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> Fix the issues that the SCSI EVS cannot be restored

.github/workflows/release.yaml
kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add release image workflow

docs/iam-policies.md
Fixes #
```release-note
NONE
```
```docs
```
=> Update iam policies

cluster/images/evs-csi-plugin/Dockerfile, docs/evs/dynamic-provisioning.md, docs/evs/evs.md, docs/obs/obs.md, docs/sfs/sfs.md, docs/sfsturbo/sfsturbo.md, pkg/evs/constants.go, pkg/evs/controllerserver.go
/kind feature
Add disk encryption support
Fixes #
```release-note
```
```docs
```
=> feat: Add disk encryption support

deploy/evs-csi-plugin/kubernetes/csi-evs-controller.yaml, deploy/evs-csi-plugin/kubernetes/csi-evs-node.yaml, docs/evs/evs-encrypted.md, docs/evs/evs.md
Fixes #109
```release-note
```
```docs
```
=> Add disk encryption example

docs/cloud-config.md
Add examples for cloud-config.
Fixes #
```release-note
NONE
```
```docs
```
=> Add examples for cloud-config

docs/evs/evs-resize.md
Fixes #
```release-note
```
```docs
```
=> fix(EVS): modifications should use apply instead of create

pkg/evs/controllerserver.go
> /kind bug
Fixes #117
```release-note
```
```docs
```
=> fix(EVS): the issue that the expansion is not executed on the node

docs/iam-policies.md
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix: add permissions used when encrypting disks on FE

deploy/evs-csi-plugin/kubernetes/csi-evs-node.yaml
Fixes #
```release-note
```
```docs
```
=> feat: add /mnt/paas volume mount 

go.mod, go.sum, pkg/sfsturbo/controllerserver.go, pkg/sfsturbo/services/volumes.go, vendor/github.com/chnsz/golangsdk/.gitignore, vendor/github.com/chnsz/golangsdk/openstack/blockstorage/v2/volumes/requests.go, vendor/github.com/chnsz/golangsdk/openstack/blockstorage/v2/volumes/results.go, vendor/github.com/chnsz/golangsdk/openstack/client.go, vendor/github.com/chnsz/golangsdk/openstack/evs/v2/cloudvolumes/requests.go, vendor/github.com/chnsz/golangsdk/openstack/evs/v2/cloudvolumes/results.go, vendor/github.com/chnsz/golangsdk/openstack/sfs_turbo/v1/shares/requests.go, vendor/github.com/chnsz/golangsdk/openstack/sfs_turbo/v1/shares/results.go, vendor/github.com/chnsz/golangsdk/openstack/utils/utils.go, vendor/github.com/chnsz/golangsdk/pagination/http.go, vendor/github.com/chnsz/golangsdk/pagination/list_all.go, vendor/modules.txt
/kind api-change
Fixes #
```release-note
```
```docs
```
=> Upgrade golangsdk dependency and fix the changed struct

docs/evs/evs-gpssd2.md, docs/evs/evs.md, examples/evs-csi-plugin/kubernetes/gpssd2-volume/pod.yaml, examples/evs-csi-plugin/kubernetes/gpssd2-volume/pvc.yaml, examples/evs-csi-plugin/kubernetes/gpssd2-volume/sc.yaml, pkg/evs/controllerserver.go, pkg/evs/services/volumes.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat(evs): supports creating GPSSD2 and ESSD2 volume

cluster/images/obs-csi-plugin/csi-connector-server.go, pkg/obs/nodeserver.go, pkg/utils/logroundtripper.go
/kind feature
Fixes #124
```release-note
```
```docs
```
=> feat(obs): OBS CSI supports custom mount options

deploy/evs-csi-plugin/kubernetes/csi-evs-controller.yaml, deploy/evs-csi-plugin/kubernetes/csi-evs-node.yaml, deploy/obs-csi-plugin/kubernetes/csi-obs-controller.yaml, deploy/obs-csi-plugin/kubernetes/csi-obs-node.yaml, deploy/sfs-csi-plugin/kubernetes/csi-sfs-controller.yaml, deploy/sfs-csi-plugin/kubernetes/csi-sfs-node.yaml, deploy/sfsturbo-csi-plugin/kubernetes/csi-sfsturbo-controller.yaml, deploy/sfsturbo-csi-plugin/kubernetes/csi-sfsturbo-node.yaml
/kind feature
Fixes #
```release-note
```
```docs
```
=> Enable hostNetwork to support pod to obtain ECS metadata information

deploy/evs-csi-plugin/kubernetes/csi-evs-controller.yaml, deploy/evs-csi-plugin/kubernetes/csi-evs-node.yaml, deploy/obs-csi-plugin/kubernetes/csi-obs-controller.yaml, deploy/obs-csi-plugin/kubernetes/csi-obs-node.yaml, deploy/sfs-csi-plugin/kubernetes/csi-sfs-controller.yaml, deploy/sfs-csi-plugin/kubernetes/csi-sfs-node.yaml, deploy/sfsturbo-csi-plugin/kubernetes/csi-sfsturbo-controller.yaml, deploy/sfsturbo-csi-plugin/kubernetes/csi-sfsturbo-node.yaml
/kind bug
Fixes #136
```release-note
```
```docs
```
=> Fix port issues caused by enabling hostNetwork

pkg/utils/file_test.go
>
> /kind design
Fixes #
```release-note
```
```docs
```
=> feat(unit): add pkg/file unit test.

pkg/utils/sha256_test.go
>
> /kind design
Fixes #
```release-note
```
```docs
```
=> feat(unit): add pkg/sha256 unit test.

pkg/utils/utils_test.go
>
> /kind design
Fixes #
```release-note
```
```docs
```
=> feat(unit): add pkg/utils unit test.

pkg/utils/aes_test.go
>
> /kind design
Fixes #
```release-note
```
```docs
```
=> feat(unit): add pkg/aes unit test

pkg/utils/logroundtripper_test.go
>
> /kind design
Fixes #
```release-note
```
```docs
```
=> feat(unit): add pkg/logroundtripper unit test

docs/cloud-config.md, pkg/config/cloud.go, pkg/sfsturbo/controllerserver.go, pkg/sfsturbo/identityserver.go, pkg/sfsturbo/nodeserver.go
>
Fixes #
```release-note
```
```docs
```
=> feat(sfsturbo): support share mount to idc server room.

docs/evs/evs.md
Fixes #
```release-note
```
```docs
```
=> update k8s version tested

pkg/config/cloud.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: add insecure to trust self-signed certificates
